describe('Verify magento-demo login', () => {
  it.only('Failed login - Invalid email', () => {
    cy.visit('https://magento.softwaretestingboard.com/')
    cy.get('.panel > .header > .authorization-link').click()
    cy.wait(20000)
    cy.get('#email').type(loginUser.invalid.invalid_email)
    cy.get('#pass').type(loginUser.valid.valid_pass)
    cy.get('.action.login.primary').click()
    cy.wait(20000)
    //cy.get('.message-error > div').should('contain', 'The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later.')
  })
  it('Failed login - Invalid Password', () => {
    cy.visit('')
    cy.get('.panel > .header > .authorization-link').click()
    cy.wait(20000)
    cy.get('#email').type(loginUser.valid.valid_email)
    cy.get('#pass').type(loginUser.invalid.invalid_pass)
    cy.get('.action.login.primary').click()
    cy.wait(20000)
    cy.get('.message-error > div').should('contain', 'The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later.')
  })
  it('Failed login - email empty', () => {
    cy.visit('')
    cy.get('.panel > .header > .authorization-link').click()
    cy.wait(20000)
    cy.get('#email').click()
    cy.get('#pass').type(loginUser.valid.valid_pass)
    cy.get('.action.login.primary').click()
    cy.wait(20000)
    cy.get('.message-error > div').should('contain', 'Invalid Form Key. Please refresh the page.')
    //cy.get('#email-error').should('contain', 'This is a required field.')
    //cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .email> .control > #email').should('contain', 'This is a required field.')
  })
  it('Failed login - password empty', () => {
    cy.visit('')
    cy.get('.panel > .header > .authorization-link').click()
    cy.wait(20000)
    cy.get('#email').type(loginUser.valid.valid_email)
    cy.get('#pass').click()
    cy.get('.action.login.primary').click()
    cy.wait(20000)
    cy.get('.message-error > div').should('contain', 'Invalid Form Key. Please refresh the page.')
    //cy.get('#email-error').should('contain', 'This is a required field.')
    //cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .password > .control > #pass').should('contain', 'This is a required field.')
  })
  it('Succes login', () => {
    cy.visit('')
    cy.get('.panel > .header > .authorization-link').click()
    cy.wait(20000)
    cy.get('#email').type(loginUser.valid.valid_email)
    cy.get('#pass').type(loginUser.valid.valid_pass)
    cy.get('.action.login.primary').click()
    cy.wait(20000)
    cy.get(':nth-child(2) > .greet > .logged-in').should('have.text','Welcome, tes tes!')
  })
})